// export const PLACES: Place[] = [
//     {
//         id: 1,
//         name: "Amber Fort",
//         slug: "amber-fort",
//         city: "Jaipur",
//         state: "Rajasthan",
//         category: "Fort",
//         subcategory: "Hill Fort",
//         description:
//             "Amber Fort is a magnificent fortress perched on a hilltop overlooking Maota Lake. Built with red sandstone and marble, it is a stunning blend of Hindu and Mughal architecture. The fort complex includes several palaces, halls, and gardens, making it one of the most visited tourist destinations in Rajasthan.",
//         history:
//             "Built in 1592 by Raja Man Singh I, Amber Fort was the capital of the Kachwaha Rajput clan until Jaipur was made the new capital. The fort took over 100 years to complete and was expanded by successive rulers including Mirza Raja Jai Singh I and Sawai Jai Singh II. The fort has witnessed numerous battles and served as the seat of power for the Kachwaha Rajputs for centuries. It was declared a UNESCO World Heritage Site in 2013 as part of the Hill Forts of Rajasthan.",
//         images: [
//     "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=1200&q=80"
// ],
//         rating: 4.9,
//         reviews: 25600,
//         timing: {
//             open: "8:00 AM",
//             close: "5:30 PM",
//             closedOn: "Open all days",
//             note: "Light & Sound Show: 6:30 PM - 7:30 PM (English), 8:00 PM - 9:00 PM (Hindi)",
//         },
//         ticket: {
//             isFree: false,
//             indian: 100,
//             foreigner: 500,
//             childIndian: 0,
//             childForeigner: 0,
//             camera: 50,
//             note: "Children below 7 years free. Composite ticket available for multiple monuments.",
//         },
//         location: {
//             address: "Devisinghpura, Amer",
//             city: "Jaipur",
//             pincode: "302001",
//             latitude: 26.9855,
//             longitude: 75.8513,
//             googleMapUrl: "https://maps.google.com/?q=26.9855,75.8513",
//             nearestAirport: "Jaipur International Airport (13 km)",
//             nearestRailway: "Jaipur Junction (11 km)",
//             distanceFromCity: "11 km from Jaipur city center",
//         },
//         bestTimeToVisit: {
//             months: "October - March",
//             season: "Winter",
//             weather: "Pleasant, 10°C - 25°C",
//             tip: "Visit early morning to avoid crowds. Sunset views are spectacular.",
//         },
//         visitDuration: {
//             minimum: "1.5 Hours",
//             recommended: "2-3 Hours",
//             extended: "4-5 Hours (with Light & Sound Show)",
//         },
//         highlights: [
//             "Sheesh Mahal (Mirror Palace)",
//             "Ganesh Pol (Painted Gateway)",
//             "Diwan-e-Aam (Hall of Public Audience)",
//             "Diwan-e-Khas (Hall of Private Audience)",
//             "Sukh Mahal (Air-conditioned Palace)",
//             "Light & Sound Show",
//             "Maota Lake View",
//             "Elephant Ride Path",
//         ],
//         tags: ["UNESCO", "Fort", "Architecture", "History", "Photography", "Heritage"],
//         facilities: [
//             "Parking",
//             "Restrooms",
//             "Guide Available",
//             "Wheelchair Accessible (Partial)",
//             "Souvenir Shop",
//             "Water",
//             "Cafe",
//         ],
//         nearbyPlaces: [
//             "Jaigarh Fort (1 km)",
//             "Nahargarh Fort (15 km)",
//             "Panna Meena Ka Kund (500m)",
//             "Anokhi Museum (2 km)",
//         ],
//         dos: [
//             "Wear comfortable walking shoes",
//             "Carry water bottle",
//             "Hire a local guide for history",
//             "Visit Sheesh Mahal",
//             "Stay for sunset views",
//         ],
//         donts: [
//             "Don't litter",
//             "Don't touch the mirror work",
//             "Don't ride elephants (animal welfare)",
//             "Don't visit during peak afternoon heat",
//         ],
//         isOpen: true,
//         isFeatured: true,
//         isPopular: true,
//         isUNESCO: true,
//         yearBuilt: "1592 AD",
//         builtBy: "Raja Man Singh I",
//         architecture: "Hindu-Mughal (Rajputana)",
//         significance: "Former capital of Kachwaha Rajputs, UNESCO World Heritage Site",
//     },
//     {
//         id: 2,
//         name: "Hawa Mahal",
//         slug: "hawa-mahal",
//         city: "Jaipur",
//         state: "Rajasthan",
//         category: "Palace",
//         subcategory: "Wind Palace",
//         description:
//             "Hawa Mahal, the 'Palace of Winds', is Jaipur's most iconic landmark. This stunning five-story structure features 953 small windows (jharokhas) decorated with intricate latticework. Built from red and pink sandstone, it was designed to allow royal women to observe street life and processions without being seen.",
//         history:
//             "Built in 1799 by Maharaja Sawai Pratap Singh, the grandson of Maharaja Sawai Jai Singh II, who founded Jaipur city. The palace was inspired by the crown of Lord Krishna. The architect Lal Chand Ustad designed this unique building as an extension of the Royal City Palace. Its honeycomb-like structure with 953 windows was designed to allow cool air to circulate through the building, hence the name 'Palace of Winds'.",
//         images: [
// "https://images.unsplash.com/photo-1603262110263-fb0112e7cc33?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1524413840003-0587428385ad?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1603262110263-fb0112e7cc33?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1524413840003-0587428385ad?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1603262110263-fb0112e7cc33?auto=format&fit=crop&w=1200&q=80"
//         ],
//         rating: 4.7,
//         reviews: 31200,
//         timing: {
//             open: "9:00 AM",
//             close: "4:30 PM",
//             closedOn: "Open all days",
//             note: "Best photography time is early morning when sunlight hits the facade.",
//         },
//         ticket: {
//             isFree: false,
//             indian: 50,
//             foreigner: 200,
//             childIndian: 0,
//             childForeigner: 0,
//             camera: 10,
//             note: "Composite ticket: ₹300 (Indian) covers 7 monuments for 2 days.",
//         },
//         location: {
//             address: "Hawa Mahal Road, Badi Choupad",
//             city: "Jaipur",
//             pincode: "302002",
//             latitude: 26.9239,
//             longitude: 75.8267,
//             googleMapUrl: "https://maps.google.com/?q=26.9239,75.8267",
//             nearestAirport: "Jaipur International Airport (12 km)",
//             nearestRailway: "Jaipur Junction (5 km)",
//             distanceFromCity: "In the heart of Jaipur old city",
//         },
//         bestTimeToVisit: {
//             months: "October - March",
//             season: "Winter",
//             weather: "Pleasant, 10°C - 25°C",
//             tip: "Visit early morning for best photographs when sunlight makes it glow pink.",
//         },
//         visitDuration: {
//             minimum: "30 Minutes",
//             recommended: "1-1.5 Hours",
//             extended: "2 Hours (with museum)",
//         },
//         highlights: [
//             "953 Jharokha Windows",
//             "Honeycomb Architecture",
//             "City View from Top Floor",
//             "Small Museum Inside",
//             "Pink Sandstone Facade",
//             "Johari Bazaar Nearby",
//             "Rajasthani Architecture",
//             "Photography Spot",
//         ],
//         tags: ["Palace", "Architecture", "Photography", "Heritage", "Iconic", "Pink City"],
//         facilities: [
//             "Restrooms",
//             "Guide Available",
//             "Nearby Parking",
//             "Souvenir Shops",
//         ],
//         nearbyPlaces: [
//             "City Palace (500m)",
//             "Jantar Mantar (400m)",
//             "Johari Bazaar (100m)",
//             "Nahargarh Fort (6 km)",
//         ],
//         dos: [
//             "Take photos from across the street for full view",
//             "Visit the top floor for panoramic city views",
//             "Explore the small museum inside",
//             "Visit early morning for best light",
//         ],
//         donts: [
//             "Don't lean on the delicate jharokhas",
//             "Don't visit during peak afternoon heat",
//             "Don't block narrow staircases",
//         ],
//         isOpen: true,
//         isFeatured: true,
//         isPopular: true,
//         isUNESCO: false,
//         yearBuilt: "1799 AD",
//         builtBy: "Maharaja Sawai Pratap Singh",
//         architecture: "Rajputana (Red & Pink Sandstone)",
//         significance: "Most photographed monument in Jaipur, Palace of Winds",
//     },
//     {
//         id: 3,
//         name: "Mehrangarh Fort",
//         slug: "mehrangarh-fort",
//         city: "Jodhpur",
//         state: "Rajasthan",
//         category: "Fort",
//         subcategory: "Hill Fort",
//         description:
//             "Mehrangarh Fort is one of the largest and most magnificent forts in India, rising 410 feet above Jodhpur city on a rocky cliff. The fort's imposing walls, some up to 36 meters high and 21 meters wide, house a museum with one of the finest collections of Rajput art, palanquins, musical instruments, costumes, and furniture.",
//         history:
//             "Built in 1459 by Rao Jodha, the founder of Jodhpur, Mehrangarh Fort has been continuously occupied for over 560 years. The fort was expanded by successive rulers and has withstood numerous attacks. Legend says that when Rao Jodha decided to build the fort, he had to displace a hermit called Cheeria Nathji who cursed the fort with droughts. To appease the curse, Rao Jodha buried a man alive in the foundations. The fort has seven gates, each built to commemorate victories in battles.",
//         images: [
// "https://images.unsplash.com/photo-1562141989-c5c79ac8f576?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1562141989-c5c79ac8f576?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1562141989-c5c79ac8f576?auto=format&fit=crop&w=1200&q=80"
//         ],
//         rating: 4.9,
//         reviews: 19800,
//         timing: {
//             open: "9:00 AM",
//             close: "5:00 PM",
//             closedOn: "Open all days",
//             note: "Last entry 4:30 PM. Zip line operates 9:00 AM - 5:00 PM separately.",
//         },
//         ticket: {
//             isFree: false,
//             indian: 100,
//             foreigner: 600,
//             childIndian: 50,
//             childForeigner: 300,
//             camera: 100,
//             note: "Audio guide: ₹180 (Hindi), ₹200 (English). Includes museum entry.",
//         },
//         location: {
//             address: "The Fort, Jodhpur",
//             city: "Jodhpur",
//             pincode: "342006",
//             latitude: 26.2981,
//             longitude: 73.0188,
//             googleMapUrl: "https://maps.google.com/?q=26.2981,73.0188",
//             nearestAirport: "Jodhpur Airport (5 km)",
//             nearestRailway: "Jodhpur Junction (3 km)",
//             distanceFromCity: "In the heart of Jodhpur city",
//         },
//         bestTimeToVisit: {
//             months: "October - March",
//             season: "Winter",
//             weather: "Cool and pleasant, 8°C - 28°C",
//             tip: "Visit during sunset for stunning views of the Blue City below.",
//         },
//         visitDuration: {
//             minimum: "2 Hours",
//             recommended: "3-4 Hours",
//             extended: "5-6 Hours (with zip line and all galleries)",
//         },
//         highlights: [
//             "Museum with Royal Artifacts",
//             "Panoramic Blue City Views",
//             "Moti Mahal (Pearl Palace)",
//             "Phool Mahal (Flower Palace)",
//             "Sound & Light Show",
//             "Flying Fox Zip Line",
//             "Chamunda Mataji Temple",
//             "7 Historic Gates",
//         ],
//         tags: ["Fort", "Museum", "Views", "Heritage", "Adventure", "Blue City"],
//         facilities: [
//             "Parking",
//             "Restrooms",
//             "Audio Guide",
//             "Restaurant",
//             "Gift Shop",
//             "Wheelchair Accessible (Partial)",
//             "Lockers",
//         ],
//         nearbyPlaces: [
//             "Jaswant Thada (1 km)",
//             "Clock Tower Market (2 km)",
//             "Umaid Bhawan Palace (5 km)",
//             "Toorji Ka Jhalra (Stepwell) (2 km)",
//         ],
//         dos: [
//             "Take the audio guide - it's excellent",
//             "Visit the museum galleries",
//             "Watch sunset from the ramparts",
//             "Try the zip line for adventure",
//         ],
//         donts: [
//             "Don't rush - the fort deserves at least 3 hours",
//             "Don't miss the cannon ball marks on gates",
//             "Don't skip the Turban Gallery",
//         ],
//         isOpen: true,
//         isFeatured: true,
//         isPopular: true,
//         isUNESCO: false,
//         yearBuilt: "1459 AD",
//         builtBy: "Rao Jodha",
//         architecture: "Rajputana (Sandstone)",
//         significance: "One of India's largest forts, 560+ years old",
//     },
//     {
//         id: 4,
//         name: "City Palace Udaipur",
//         slug: "city-palace-udaipur",
//         city: "Udaipur",
//         state: "Rajasthan",
//         category: "Palace",
//         subcategory: "Royal Palace Complex",
//         description:
//             "City Palace of Udaipur is a magnificent palace complex situated on the eastern bank of Lake Pichola. It is the largest palace complex in Rajasthan, built over a period of nearly 400 years by successive Mewar rulers. The palace seamlessly blends Rajasthani and Mughal architectural styles with stunning balconies, towers, and cupolas overlooking the lake.",
//         history:
//             "Construction began in 1559 by Maharana Udai Singh II, who founded Udaipur after being advised by a sage to build his capital here. The palace was expanded over four centuries by 22 successive Maharanas of Mewar. Unlike many other Rajput rulers, the Mewar dynasty never submitted to the Mughals, making this palace a symbol of Rajput pride and resistance. Today, part of the palace is a museum, part is a luxury hotel, and part remains the residence of the Mewar royal family.",
//         images: [
// "https://images.unsplash.com/photo-1585141974416-24a1b0268598?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1615552980649-db3722e0325d?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1602643163983-ed0babc39797?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1590001155093-a3c66ab0c3ff?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1585141974416-24a1b0268598?auto=format&fit=crop&w=1200&q=80"
//         ],
//         rating: 4.8,
//         reviews: 22100,
//         timing: {
//             open: "9:30 AM",
//             close: "5:30 PM",
//             closedOn: "Open all days",
//             note: "Last entry at 5:00 PM. Crystal Gallery has separate timing and ticket.",
//         },
//         ticket: {
//             isFree: false,
//             indian: 300,
//             foreigner: 700,
//             childIndian: 100,
//             childForeigner: 350,
//             camera: 250,
//             note: "Crystal Gallery: Extra ₹500 (Indian), ₹700 (Foreigner). Guide: ₹200-400.",
//         },
//         location: {
//             address: "Old City, Udaipur",
//             city: "Udaipur",
//             pincode: "313001",
//             latitude: 24.5764,
//             longitude: 73.6831,
//             googleMapUrl: "https://maps.google.com/?q=24.5764,73.6831",
//             nearestAirport: "Maharana Pratap Airport (24 km)",
//             nearestRailway: "Udaipur City Railway Station (3 km)",
//             distanceFromCity: "In the heart of old Udaipur",
//         },
//         bestTimeToVisit: {
//             months: "September - March",
//             season: "Winter / Post-Monsoon",
//             weather: "Pleasant, 10°C - 30°C",
//             tip: "Visit during sunset for magical Lake Pichola views. Monsoon makes the lake full and beautiful.",
//         },
//         visitDuration: {
//             minimum: "2 Hours",
//             recommended: "3-4 Hours",
//             extended: "5-6 Hours (with Crystal Gallery and boat ride)",
//         },
//         highlights: [
//             "Mor Chowk (Peacock Courtyard)",
//             "Crystal Gallery",
//             "Lake Pichola Views",
//             "Amar Vilas Garden",
//             "Badi Mahal (Garden Palace)",
//             "Manak Mahal (Ruby Palace)",
//             "Sheesh Mahal (Mirror Palace)",
//             "Vintage Car Collection",
//         ],
//         tags: ["Palace", "Museum", "Lake View", "Heritage", "Architecture", "Royal"],
//         facilities: [
//             "Parking",
//             "Restrooms",
//             "Guide Available",
//             "Cafe",
//             "Gift Shop",
//             "Wheelchair Accessible (Partial)",
//         ],
//         nearbyPlaces: [
//             "Lake Pichola (Adjacent)",
//             "Jagdish Temple (200m)",
//             "Bagore Ki Haveli (500m)",
//             "Saheliyon Ki Bari (3 km)",
//         ],
//         dos: [
//             "Visit the Crystal Gallery",
//             "Take a sunset boat ride on Lake Pichola",
//             "Explore the museum sections thoroughly",
//             "Hire a guide for detailed history",
//         ],
//         donts: [
//             "Don't touch the antique artifacts",
//             "Don't miss the Mor Chowk peacock mosaics",
//             "Don't skip the rooftop views",
//         ],
//         isOpen: true,
//         isFeatured: true,
//         isPopular: true,
//         isUNESCO: false,
//         yearBuilt: "1559 AD",
//         builtBy: "Maharana Udai Singh II",
//         architecture: "Rajasthani-Mughal Blend",
//         significance: "Largest palace complex in Rajasthan, seat of Mewar dynasty",
//     },
//     {
//         id: 5,
//         name: "Jaisalmer Fort",
//         slug: "jaisalmer-fort",
//         city: "Jaisalmer",
//         state: "Rajasthan",
//         category: "Fort",
//         subcategory: "Living Fort",
//         description:
//             "Jaisalmer Fort, also known as Sonar Quila (Golden Fort), is one of the world's few 'living forts' where approximately 3,000 people still reside within its walls. Built entirely of golden-yellow sandstone, the fort glows like gold in the sunlight, especially during sunrise and sunset, earning it the name Golden Fort.",
//         history:
//             "Built in 1156 AD by Rawal Jaisal, a Bhati Rajput ruler, Jaisalmer Fort stands on Trikuta Hill in the heart of the Thar Desert. The fort has survived numerous attacks from the Delhi Sultanate and neighboring kingdoms. It is one of the very few forts in the world that is still inhabited by a quarter of the city's population. The fort was declared a UNESCO World Heritage Site in 2013 as part of the Hill Forts of Rajasthan. Its strategic location on the ancient Silk Route made Jaisalmer a wealthy trading center.",
//         images: [
// "https://images.unsplash.com/photo-1585141974416-24a1b0268598?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1615552980649-db3722e0325d?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1602643163983-ed0babc39797?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1590001155093-a3c66ab0c3ff?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1585141974416-24a1b0268598?auto=format&fit=crop&w=1200&q=80"
//         ],
//         rating: 4.8,
//         reviews: 17500,
//         timing: {
//             open: "9:00 AM",
//             close: "6:00 PM",
//             closedOn: "Open all days",
//             note: "Fort walls are accessible all day as people live inside. Museum has fixed timings.",
//         },
//         ticket: {
//             isFree: false,
//             indian: 50,
//             foreigner: 250,
//             childIndian: 0,
//             childForeigner: 0,
//             camera: 100,
//             note: "Fort entry is free. Ticket is for the Palace Museum and Jain Temples inside.",
//         },
//         location: {
//             address: "Fort Road, Jaisalmer",
//             city: "Jaisalmer",
//             pincode: "345001",
//             latitude: 26.9124,
//             longitude: 70.9083,
//             googleMapUrl: "https://maps.google.com/?q=26.9124,70.9083",
//             nearestAirport: "Jaisalmer Airport (17 km)",
//             nearestRailway: "Jaisalmer Railway Station (1 km)",
//             distanceFromCity: "In the center of Jaisalmer city",
//         },
//         bestTimeToVisit: {
//             months: "November - February",
//             season: "Winter",
//             weather: "Cool, 5°C - 25°C",
//             tip: "Visit during sunrise or sunset when the fort literally glows golden.",
//         },
//         visitDuration: {
//             minimum: "2 Hours",
//             recommended: "3-4 Hours",
//             extended: "Full Day (exploring streets, shops, temples)",
//         },
//         highlights: [
//             "Golden Sandstone Architecture",
//             "Living Fort (3000+ residents)",
//             "Jain Temples (12th-15th century)",
//             "Raj Mahal (Royal Palace)",
//             "Merchant Havelis",
//             "Fort Ramparts & Bastions",
//             "Local Craft Shops",
//             "Rooftop Restaurants with Desert Views",
//         ],
//         tags: ["UNESCO", "Fort", "Living Fort", "Desert", "Heritage", "Architecture"],
//         facilities: [
//             "Restrooms",
//             "Restaurants",
//             "Shops",
//             "Guide Available",
//             "ATM Inside",
//         ],
//         nearbyPlaces: [
//             "Patwon Ki Haveli (500m)",
//             "Gadisar Lake (1 km)",
//             "Sam Sand Dunes (42 km)",
//             "Bada Bagh (6 km)",
//         ],
//         dos: [
//             "Walk through the narrow streets",
//             "Visit the Jain Temples inside",
//             "Watch sunset from the fort walls",
//             "Try local Rajasthani food at rooftop cafes",
//         ],
//         donts: [
//             "Don't use plastic inside the fort",
//             "Don't damage the sandstone walls",
//             "Don't bargain aggressively with local artisans",
//         ],
//         isOpen: true,
//         isFeatured: true,
//         isPopular: true,
//         isUNESCO: true,
//         yearBuilt: "1156 AD",
//         builtBy: "Rawal Jaisal",
//         architecture: "Rajputana (Golden Sandstone)",
//         significance: "One of the world's few living forts, UNESCO World Heritage Site",
//     },
//     {
//         id: 6,
//         name: "Lake Pichola",
//         slug: "lake-pichola",
//         city: "Udaipur",
//         state: "Rajasthan",
//         category: "Lake",
//         subcategory: "Artificial Lake",
//         description:
//             "Lake Pichola is one of the most picturesque and oldest artificial lakes in India. The serene lake is surrounded by hills, palaces, temples, and ghats, creating a magical setting. The famous Lake Palace (Jag Niwas) and Jag Mandir palace appear to float on the water, making it one of the most romantic locations in India.",
//         history:
//             "Created in 1362 AD by a Banjara tribesman named Pichhu (or Pichhola), the lake was originally a small water body. Maharana Udai Singh II was so captivated by the lake that he decided to build his new capital, Udaipur, on its banks in 1559. Later, Maharana Udai Singh II enlarged the lake by building a dam. Two island palaces - Jag Niwas (now Lake Palace Hotel) and Jag Mandir - were built on the lake, adding to its grandeur.",
//         images: [
// "https://images.unsplash.com/photo-1585141974416-24a1b0268598?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1615552980649-db3722e0325d?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1585141974416-24a1b0268598?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1615552980649-db3722e0325d?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1585141974416-24a1b0268598?auto=format&fit=crop&w=1200&q=80"
//         ],
//         rating: 4.8,
//         reviews: 20300,
//         timing: {
//             open: "All Day",
//             close: "All Night",
//             closedOn: "Open all days",
//             note: "Boat rides: 10:00 AM to 5:00 PM. Sunset boat rides are most popular.",
//         },
//         ticket: {
//             isFree: true,
//             indian: 0,
//             foreigner: 0,
//             childIndian: 0,
//             childForeigner: 0,
//             camera: 0,
//             note: "Lake viewing is free. Boat ride: ₹400-800 per person. Sunset cruise: ₹700-1200.",
//         },
//         location: {
//             address: "Old City, Udaipur",
//             city: "Udaipur",
//             pincode: "313001",
//             latitude: 24.5711,
//             longitude: 73.6778,
//             googleMapUrl: "https://maps.google.com/?q=24.5711,73.6778",
//             nearestAirport: "Maharana Pratap Airport (24 km)",
//             nearestRailway: "Udaipur City Railway Station (3 km)",
//             distanceFromCity: "In the heart of Udaipur",
//         },
//         bestTimeToVisit: {
//             months: "September - March",
//             season: "Post-Monsoon / Winter",
//             weather: "Pleasant, 12°C - 28°C",
//             tip: "The lake is fullest and most beautiful after monsoon (Sept-Nov). Sunset boat rides are magical.",
//         },
//         visitDuration: {
//             minimum: "1 Hour",
//             recommended: "2-3 Hours (with boat ride)",
//             extended: "Half Day (with nearby ghats and temples)",
//         },
//         highlights: [
//             "Sunset Boat Ride",
//             "Lake Palace (Jag Niwas) View",
//             "Jag Mandir Island",
//             "City Palace Backdrop",
//             "Ambrai Ghat",
//             "Gangaur Ghat",
//             "Mountain Reflections",
//             "Photography Paradise",
//         ],
//         tags: ["Lake", "Romantic", "Boat Ride", "Sunset", "Photography", "Free Entry"],
//         facilities: [
//             "Boat Rides",
//             "Ghats",
//             "Nearby Restaurants",
//             "Parking",
//             "Photography Spots",
//         ],
//         nearbyPlaces: [
//             "City Palace (Adjacent)",
//             "Jagdish Temple (500m)",
//             "Bagore Ki Haveli (300m)",
//             "Ambrai Ghat (200m)",
//         ],
//         dos: [
//             "Take a sunset boat ride",
//             "Visit Ambrai Ghat for best photos",
//             "Walk along the ghats at sunset",
//             "Try rooftop restaurants with lake views",
//         ],
//         donts: [
//             "Don't throw anything in the lake",
//             "Don't swim in the lake",
//             "Don't miss the sunset",
//         ],
//         isOpen: true,
//         isFeatured: true,
//         isPopular: true,
//         isUNESCO: false,
//         yearBuilt: "1362 AD",
//         builtBy: "Pichhu Banjara (tribesman)",
//         architecture: "Natural & Artificial Lake",
//         significance: "Oldest artificial lake in Udaipur, Rajasthan's most romantic spot",
//     },
//     {
//         id: 7,
//         name: "Sam Sand Dunes",
//         slug: "sam-sand-dunes",
//         city: "Jaisalmer",
//         state: "Rajasthan",
//         category: "Desert",
//         subcategory: "Sand Dunes",
//         description:
//             "Sam Sand Dunes is one of the most popular desert destinations in Rajasthan, located 42 km from Jaisalmer in the Thar Desert. The majestic golden sand dunes rise up to 30-60 meters and offer a quintessential desert experience including camel safaris, jeep rides, desert camping, folk music, and dance under the stars.",
//         history:
//             "The Sam village and its sand dunes have been an important settlement along the ancient Silk Route trade corridor. Caravans carrying goods between India and Central Asia would pass through this area, and Sam served as a resting point. The dunes have been shaped over thousands of years by wind patterns of the Thar Desert. The Desert National Park nearby is home to the endangered Great Indian Bustard and other desert wildlife.",
//         images: [
// "https://images.unsplash.com/photo-1542401886-65d6c61db217?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1542401886-65d6c61db217?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=1200&q=80"
//         ],
//         rating: 4.7,
//         reviews: 15600,
//         timing: {
//             open: "All Day",
//             close: "All Night",
//             closedOn: "Open all days",
//             note: "Best visited 3:00 PM - 10:00 AM next day. Camel safari starts around 3:30 PM.",
//         },
//         ticket: {
//             isFree: true,
//             indian: 0,
//             foreigner: 0,
//             childIndian: 0,
//             childForeigner: 0,
//             camera: 0,
//             note: "Dunes entry is free. Camel ride: ₹300-800. Desert camp: ₹1500-5000/night. Jeep safari: ₹1000-2000.",
//         },
//         location: {
//             address: "Sam Village, Thar Desert",
//             city: "Jaisalmer",
//             pincode: "345001",
//             latitude: 26.7763,
//             longitude: 70.5283,
//             googleMapUrl: "https://maps.google.com/?q=26.7763,70.5283",
//             nearestAirport: "Jaisalmer Airport (55 km)",
//             nearestRailway: "Jaisalmer Railway Station (42 km)",
//             distanceFromCity: "42 km from Jaisalmer city",
//         },
//         bestTimeToVisit: {
//             months: "November - February",
//             season: "Winter",
//             weather: "Cool nights 5°C, warm days 25°C",
//             tip: "Visit during Desert Festival (Feb) for the best cultural experience. Avoid May-July (extreme heat 50°C+).",
//         },
//         visitDuration: {
//             minimum: "3-4 Hours (evening safari)",
//             recommended: "Overnight (desert camping)",
//             extended: "2 Days (full desert experience)",
//         },
//         highlights: [
//             "Camel Safari at Sunset",
//             "Desert Camping Under Stars",
//             "Rajasthani Folk Music & Dance",
//             "Jeep Safari on Dunes",
//             "Sunrise Over Sand Dunes",
//             "Star Gazing (No Light Pollution)",
//             "Traditional Rajasthani Dinner",
//             "Sand Dune Photography",
//         ],
//         tags: ["Desert", "Safari", "Camping", "Adventure", "Free Entry", "Photography"],
//         facilities: [
//             "Desert Camps",
//             "Camel Rides",
//             "Jeep Safari",
//             "Cultural Programs",
//             "Restrooms (at camps)",
//             "Food (at camps)",
//         ],
//         nearbyPlaces: [
//             "Jaisalmer Fort (42 km)",
//             "Desert National Park (20 km)",
//             "Kuldhara Ghost Village (25 km)",
//             "Khaba Fort (35 km)",
//         ],
//         dos: [
//             "Stay overnight for the full experience",
//             "Carry warm clothes for cold desert nights",
//             "Apply sunscreen during daytime",
//             "Try traditional dal-bati-churma dinner",
//         ],
//         donts: [
//             "Don't leave plastic in the desert",
//             "Don't visit during summer (May-July)",
//             "Don't walk barefoot on hot sand during daytime",
//             "Don't drive vehicles on protected dune areas",
//         ],
//         isOpen: true,
//         isFeatured: true,
//         isPopular: true,
//         isUNESCO: false,
//         yearBuilt: "Natural Formation",
//         builtBy: "Nature (Thar Desert)",
//         architecture: "Natural Desert Landscape",
//         significance: "Most popular desert destination in Rajasthan, Silk Route history",
//     },
//     {
//         id: 8,
//         name: "Ranthambore National Park",
//         slug: "ranthambore-national-park",
//         city: "Sawai Madhopur",
//         state: "Rajasthan",
//         category: "Wildlife",
//         subcategory: "National Park / Tiger Reserve",
//         description:
//             "Ranthambore National Park is one of India's most famous wildlife sanctuaries and a premier tiger reserve. Spread over 1,334 sq km, the park is home to Bengal tigers, leopards, crocodiles, and over 300 species of birds. The 10th-century Ranthambore Fort within the park adds a unique historical dimension to the wildlife experience.",
//         history:
//             "Ranthambore was the hunting ground of the Maharajas of Jaipur for centuries. The 10th-century Ranthambore Fort within the park is believed to have been built by the Chauhan dynasty. The fort has changed hands many times between Rajputs and the Delhi Sultanate. The area was declared a wildlife sanctuary in 1955, became part of Project Tiger in 1973, and was declared a National Park in 1980. It is named after the historic Ranthambore Fort. Today it is one of the best places in the world to see wild Bengal tigers in their natural habitat.",
//         images: [
// "https://images.unsplash.com/photo-1602491453977-63adc9f166b4?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1581888227599-779811939961?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1602491453977-63adc9f166b4?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1581888227599-779811939961?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1602491453977-63adc9f166b4?auto=format&fit=crop&w=1200&q=80"
//         ],
//         rating: 4.8,
//         reviews: 14200,
//         timing: {
//             open: "6:00 AM (Oct-Mar) / 6:30 AM (Apr-Jun)",
//             close: "6:00 PM (varies by season)",
//             closedOn: "Closed July 1 - September 30 (Monsoon)",
//             note: "Two safari slots: Morning (6:00/6:30 AM - 10:00 AM) and Afternoon (2:30 PM - 6:00 PM).",
//         },
//         ticket: {
//             isFree: false,
//             indian: 200,
//             foreigner: 1000,
//             childIndian: 100,
//             childForeigner: 500,
//             camera: 0,
//             note: "Jeep Safari: ₹2500-3000 (Indian), ₹7000+ (Foreigner). Canter (20-seater): ₹800-1000. Book online at rajasthanwildlife.in.",
//         },
//         location: {
//             address: "Ranthambore Road, Sawai Madhopur",
//             city: "Sawai Madhopur",
//             pincode: "322001",
//             latitude: 26.0173,
//             longitude: 76.5026,
//             googleMapUrl: "https://maps.google.com/?q=26.0173,76.5026",
//             nearestAirport: "Jaipur Airport (180 km)",
//             nearestRailway: "Sawai Madhopur Railway Station (11 km)",
//             distanceFromCity: "11 km from Sawai Madhopur",
//         },
//         bestTimeToVisit: {
//             months: "October - June (Open Season)",
//             season: "Winter (Oct-Feb) best, Summer (Apr-Jun) highest tiger sightings",
//             weather: "10°C - 45°C (varies greatly by season)",
//             tip: "April-June has highest tiger sighting probability as animals come to water sources. Book safaris well in advance.",
//         },
//         visitDuration: {
//             minimum: "1 Safari (Half Day)",
//             recommended: "2-3 Safaris (2 Days)",
//             extended: "4-6 Safaris (3 Days) for best tiger sighting chances",
//         },
//         highlights: [
//             "Bengal Tiger Sightings",
//             "Ranthambore Fort (10th Century)",
//             "Padam Lake & Rajbagh Ruins",
//             "Leopard Sightings",
//             "Marsh Crocodiles",
//             "300+ Bird Species",
//             "Jeep & Canter Safari",
//             "Photography Opportunities",
//         ],
//         tags: ["Wildlife", "Tiger", "Safari", "Nature", "Photography", "National Park"],
//         facilities: [
//             "Safari Booking",
//             "Parking",
//             "Restrooms",
//             "Nearby Hotels",
//             "Guide (Mandatory)",
//             "Interpretation Center",
//         ],
//         nearbyPlaces: [
//             "Ranthambore Fort (Inside Park)",
//             "Sawai Madhopur City (11 km)",
//             "Surwal Lake (25 km)",
//             "Khandar Fort (40 km)",
//         ],
//         dos: [
//             "Book safari online well in advance",
//             "Carry binoculars and camera with zoom lens",
//             "Wear earthy colors (khaki, green, brown)",
//             "Be patient and quiet during safari",
//         ],
//         donts: [
//             "Don't wear bright colors",
//             "Don't make loud noises",
//             "Don't litter in the park",
//             "Don't use flash photography",
//             "Don't stand in the vehicle",
//         ],
//         isOpen: true,
//         isFeatured: true,
//         isPopular: true,
//         isUNESCO: false,
//         yearBuilt: "Sanctuary: 1955, National Park: 1980",
//         builtBy: "Nature / Government of India",
//         architecture: "Natural Forest & 10th Century Fort",
//         significance: "India's best tiger reserve, Project Tiger site since 1973",
//     },
//     {
//         id: 9,
//         name: "Pushkar Lake & Brahma Temple",
//         slug: "pushkar-lake-brahma-temple",
//         city: "Pushkar",
//         state: "Rajasthan",
//         category: "Temple",
//         subcategory: "Sacred Lake & Temple",
//         description:
//             "Pushkar Lake is one of the most sacred lakes in Hinduism, believed to have been created when Lord Brahma dropped a lotus flower from his hand. The town of Pushkar is built around this holy lake with 52 bathing ghats and is home to the only Brahma Temple in the world. The annual Pushkar Camel Fair attracts visitors from across the globe.",
//         history:
//             "According to Hindu mythology, Lord Brahma performed a yajna (fire sacrifice) at Pushkar after a lotus fell from his hands and created the lake. The Brahma Temple was originally built in the 14th century and has been rebuilt several times. Pushkar is one of the five sacred dhams (pilgrimage sites) for Hindus. The town has been a pilgrimage center for over 2,000 years and finds mention in ancient texts like the Mahabharata and Padma Purana. The Pushkar Camel Fair dates back centuries and is now one of the world's largest camel fairs.",
//         images: [
// "https://images.unsplash.com/photo-1477584308802-e9c378852d9a?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1524413840003-0587428385ad?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1603262110263-fb0112e7cc33?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=1200&q=80"
//         ],
//         rating: 4.6,
//         reviews: 12400,
//         timing: {
//             open: "5:00 AM",
//             close: "9:00 PM",
//             closedOn: "Open all days",
//             note: "Brahma Temple: 6:30 AM - 8:30 PM. Aarti at sunrise and sunset. Photography restricted inside temple.",
//         },
//         ticket: {
//             isFree: true,
//             indian: 0,
//             foreigner: 0,
//             childIndian: 0,
//             childForeigner: 0,
//             camera: 0,
//             note: "Entry is free. Be wary of unsolicited 'puja' ceremonies at ghats that demand donations. Politely decline if not interested.",
//         },
//         location: {
//             address: "Pushkar Town",
//             city: "Pushkar",
//             pincode: "305022",
//             latitude: 26.4899,
//             longitude: 74.5511,
//             googleMapUrl: "https://maps.google.com/?q=26.4899,74.5511",
//             nearestAirport: "Jaipur Airport (150 km)",
//             nearestRailway: "Ajmer Junction (15 km)",
//             distanceFromCity: "15 km from Ajmer",
//         },
//         bestTimeToVisit: {
//             months: "October - March",
//             season: "Winter / Festival Season",
//             weather: "Pleasant, 8°C - 28°C",
//             tip: "Visit during Pushkar Camel Fair (November) for the most vibrant experience. Kartik Purnima is the holiest day.",
//         },
//         visitDuration: {
//             minimum: "2-3 Hours",
//             recommended: "Half Day",
//             extended: "1-2 Days (during Camel Fair)",
//         },
//         highlights: [
//             "Only Brahma Temple in the World",
//             "Sacred Lake with 52 Ghats",
//             "Pushkar Camel Fair (November)",
//             "Sunset Aarti at Lake",
//             "Savitri Temple (hilltop)",
//             "Varaha Temple",
//             "Rangji Temple",
//             "Colorful Markets & Cafes",
//         ],
//         tags: ["Temple", "Spiritual", "Lake", "Free Entry", "Festival", "Sacred"],
//         facilities: [
//             "Ghats",
//             "Restrooms",
//             "Nearby Hotels",
//             "Markets",
//             "Cafes",
//             "Parking",
//         ],
//         nearbyPlaces: [
//             "Savitri Temple (Hilltop, 2 km trek)",
//             "Ajmer Sharif Dargah (15 km)",
//             "Rose Garden (3 km)",
//             "Old Rangi Temple (1 km)",
//         ],
//         dos: [
//             "Remove shoes before entering temple and ghats",
//             "Respect the sacred atmosphere",
//             "Visit during sunrise or sunset aarti",
//             "Try the local malpua (sweet)",
//         ],
//         donts: [
//             "Don't take photos inside the Brahma Temple",
//             "Don't eat non-veg or drink alcohol (holy town)",
//             "Don't accept unsolicited puja at ghats",
//             "Don't throw anything in the lake",
//         ],
//         isOpen: true,
//         isFeatured: false,
//         isPopular: true,
//         isUNESCO: false,
//         yearBuilt: "14th Century (Temple), Ancient (Lake)",
//         builtBy: "Various rulers over centuries",
//         architecture: "Temple Architecture",
//         significance: "Only Brahma Temple in the world, one of 5 sacred Hindu dhams",
//     },
//     {
//         id: 10,
//         name: "Nahargarh Fort",
//         slug: "nahargarh-fort",
//         city: "Jaipur",
//         state: "Rajasthan",
//         category: "Fort",
//         subcategory: "Hill Fort",
//         description:
//             "Nahargarh Fort stands on the edge of the Aravalli Hills, overlooking the city of Jaipur. Originally named Sudarshangarh, it was later renamed Nahargarh ('Abode of Tigers'). The fort offers the most spectacular panoramic views of Jaipur city, especially at sunset and night. It is a popular hangout spot for locals and tourists alike.",
//         history:
//             "Built in 1734 by Maharaja Sawai Jai Singh II as a retreat, Nahargarh Fort was later extended by Sawai Ram Singh and Sawai Madho Singh. The fort was never attacked in its history but served as a strong defensive position. Legend says a Rathore prince's spirit haunted the fort during construction, and it was named Nahargarh (Tiger's Abode) to appease the spirit. In 1868, many Europeans were sheltered here during the Sepoy Mutiny. The Madhavendra Bhawan inside the fort has identical suites for the king's twelve queens.",
//         images: [
// "https://images.unsplash.com/photo-1477584308802-e9c378852d9a?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1524413840003-0587428385ad?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1603262110263-fb0112e7cc33?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=1200&q=80"
//         ],
//         rating: 4.6,
//         reviews: 16800,
//         timing: {
//             open: "10:00 AM",
//             close: "5:30 PM",
//             closedOn: "Open all days",
//             note: "The road to the fort is accessible till late evening. Sunset and night views are spectacular.",
//         },
//         ticket: {
//             isFree: false,
//             indian: 50,
//             foreigner: 200,
//             childIndian: 0,
//             childForeigner: 0,
//             camera: 30,
//             note: "Vehicle entry: ₹50. Night visit to the restaurant/cafe area doesn't require fort ticket.",
//         },
//         location: {
//             address: "Krishna Nagar, Brahampuri",
//             city: "Jaipur",
//             pincode: "302002",
//             latitude: 26.9378,
//             longitude: 75.8150,
//             googleMapUrl: "https://maps.google.com/?q=26.9378,75.8150",
//             nearestAirport: "Jaipur International Airport (18 km)",
//             nearestRailway: "Jaipur Junction (7 km)",
//             distanceFromCity: "6 km from Jaipur city center",
//         },
//         bestTimeToVisit: {
//             months: "October - March",
//             season: "Winter",
//             weather: "Pleasant, 10°C - 25°C",
//             tip: "Visit during sunset for the most breathtaking views of Jaipur city lit up below.",
//         },
//         visitDuration: {
//             minimum: "1 Hour",
//             recommended: "2-3 Hours",
//             extended: "3-4 Hours (with sunset and dinner at rooftop restaurant)",
//         },
//         highlights: [
//             "Panoramic Jaipur City Views",
//             "Madhavendra Bhawan (12 Queen Suites)",
//             "Sunset Point",
//             "Night City View",
//             "Wax Museum",
//             "Biological Park (at foothills)",
//             "Rooftop Restaurant",
//             "Scenic Drive to Fort",
//         ],
//         tags: ["Fort", "Views", "Sunset", "Photography", "Heritage", "Romantic"],
//         facilities: [
//             "Parking",
//             "Restaurant",
//             "Restrooms",
//             "Cafe",
//             "Guide Available",
//             "Wax Museum",
//         ],
//         nearbyPlaces: [
//             "Jaigarh Fort (Connected by wall)",
//             "Amber Fort (8 km)",
//             "Jal Mahal (4 km)",
//             "Hawa Mahal (6 km)",
//         ],
//         dos: [
//             "Visit during sunset",
//             "Drive up the winding road for views",
//             "Visit Madhavendra Bhawan",
//             "Have dinner at the rooftop restaurant",
//         ],
//         donts: [
//             "Don't drive recklessly on the winding road",
//             "Don't visit only during daytime - sunset is the highlight",
//             "Don't litter at viewpoints",
//         ],
//         isOpen: true,
//         isFeatured: false,
//         isPopular: true,
//         isUNESCO: false,
//         yearBuilt: "1734 AD",
//         builtBy: "Maharaja Sawai Jai Singh II",
//         architecture: "Indo-European (Rajputana)",
//         significance: "Best viewpoint of Jaipur, never conquered fort",
//     },
//     {
//         id: 11,
//         name: "Dilwara Temples",
//         slug: "dilwara-temples",
//         city: "Mount Abu",
//         state: "Rajasthan",
//         category: "Temple",
//         subcategory: "Jain Temple Complex",
//         description:
//             "The Dilwara Temples in Mount Abu are considered the finest examples of Jain temple architecture in India. Built between the 11th and 13th centuries, these five marble temples are renowned for their extraordinary marble carvings, so intricately detailed that they rival the Taj Mahal in craftsmanship. The marble work is so fine that it appears translucent in places.",
//         history:
//             "The Dilwara Temples were built by Vimal Shah and Tejpal Shah, ministers of the Solanki rulers of Gujarat. The oldest temple, Vimal Vasahi, was built in 1031 AD and is dedicated to the first Jain Tirthankara, Adinath. The Luna Vasahi temple, built in 1230 AD by brothers Tejpal and Vastupal, is dedicated to the 22nd Tirthankara, Neminath. Despite the simple exterior, the interiors display some of the most intricate marble carvings ever created by human hands.",
//         images: [
// "https://images.unsplash.com/photo-1477584308802-e9c378852d9a?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1524413840003-0587428385ad?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1603262110263-fb0112e7cc33?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=1200&q=80"
//         ],
//         rating: 4.8,
//         reviews: 8900,
//         timing: {
//             open: "12:00 PM",
//             close: "5:00 PM",
//             closedOn: "Open all days",
//             note: "For Jains: 6:00 AM - 12:00 PM. Non-Jain visitors: 12:00 PM - 5:00 PM only. Photography is NOT allowed inside.",
//         },
//         ticket: {
//             isFree: true,
//             indian: 0,
//             foreigner: 0,
//             childIndian: 0,
//             childForeigner: 0,
//             camera: 0,
//             note: "Entry is free. Photography is strictly prohibited inside all temples. Mobile phones must be kept outside.",
//         },
//         location: {
//             address: "Dilwara Road, Mount Abu",
//             city: "Mount Abu",
//             pincode: "307501",
//             latitude: 24.6109,
//             longitude: 72.7262,
//             googleMapUrl: "https://maps.google.com/?q=24.6109,72.7262",
//             nearestAirport: "Udaipur Airport (185 km)",
//             nearestRailway: "Abu Road Railway Station (28 km)",
//             distanceFromCity: "2.5 km from Mount Abu town center",
//         },
//         bestTimeToVisit: {
//             months: "November - February",
//             season: "Winter",
//             weather: "Cool, 5°C - 22°C",
//             tip: "Visit on weekdays to avoid crowds. The marble carvings are best appreciated slowly.",
//         },
//         visitDuration: {
//             minimum: "1 Hour",
//             recommended: "2-3 Hours",
//             extended: "3-4 Hours (with detailed study of carvings)",
//         },
//         highlights: [
//             "Vimal Vasahi Temple (1031 AD)",
//             "Luna Vasahi Temple (1230 AD)",
//             "Extraordinary Marble Carvings",
//             "48 Pillars - Each Unique",
//             "Ceiling Carvings (Rang Mandapa)",
//             "Elephant Procession Carving",
//             "Lotus Flower Ceiling",
//             "Translucent Marble Work",
//         ],
//         tags: ["Temple", "Architecture", "Jain", "Marble", "Free Entry", "Heritage"],
//         facilities: [
//             "Shoe Storage",
//             "Restrooms",
//             "Guide Available",
//             "Parking",
//             "Water",
//         ],
//         nearbyPlaces: [
//             "Nakki Lake (2.5 km)",
//             "Guru Shikhar (15 km)",
//             "Achalgarh Fort (11 km)",
//             "Sunset Point (3 km)",
//         ],
//         dos: [
//             "Remove shoes and all leather items before entering",
//             "Spend time admiring the ceiling carvings",
//             "Visit all 5 temples",
//             "Maintain silence and reverence",
//         ],
//         donts: [
//             "Absolutely NO photography or videography",
//             "Don't carry mobile phones inside",
//             "Don't wear leather items (belts, bags)",
//             "Don't touch the marble carvings",
//         ],
//         isOpen: true,
//         isFeatured: true,
//         isPopular: true,
//         isUNESCO: false,
//         yearBuilt: "1031 - 1230 AD",
//         builtBy: "Vimal Shah & Tejpal Shah",
//         architecture: "Jain Temple Architecture (White Marble)",
//         significance: "Finest Jain temples in India, unparalleled marble craftsmanship",
//     },
//     {
//         id: 12,
//         name: "Junagarh Fort",
//         slug: "junagarh-fort",
//         city: "Bikaner",
//         state: "Rajasthan",
//         category: "Fort",
//         subcategory: "Ground Fort",
//         description:
//             "Junagarh Fort is a unique ground-level fort (not on a hill) in Bikaner that has never been conquered. Built with red sandstone and marble, the fort complex houses a stunning collection of palaces, temples, and pavilions. Unlike most Rajasthani forts built on hilltops, Junagarh stands on the desert plain, surrounded by a moat.",
//         history:
//             "Built in 1593 by Raja Rai Singh, one of Mughal Emperor Akbar's most distinguished generals, Junagarh Fort is unique as it was built on flat ground rather than a hilltop. Despite this, the fort was never conquered. Raja Rai Singh used the wealth from his military campaigns under the Mughal Empire to build this magnificent fort. The fort was later expanded by his successors over the next five centuries. The name 'Junagarh' (Old Fort) was given by the 20th-century ruler Maharaja Ganga Singh when he moved to the new Lalgarh Palace.",
//         images: [
// "https://images.unsplash.com/photo-1585141974416-24a1b0268598?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1615552980649-db3722e0325d?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1602643163983-ed0babc39797?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1590001155093-a3c66ab0c3ff?auto=format&fit=crop&w=1200&q=80",
//     "https://images.unsplash.com/photo-1585141974416-24a1b0268598?auto=format&fit=crop&w=1200&q=80"
//         ],
//         rating: 4.6,
//         reviews: 7800,
//         timing: {
//             open: "10:00 AM",
//             close: "4:30 PM",
//             closedOn: "Open all days",
//             note: "Last entry at 4:00 PM. Audio guide available in multiple languages.",
//         },
//         ticket: {
//             isFree: false,
//             indian: 50,
//             foreigner: 300,
//             childIndian: 30,
//             childForeigner: 150,
//             camera: 50,
//             note: "Audio guide: ₹100 (Hindi), ₹150 (English/Others). Guide: ₹200-300.",
//         },
//         location: {
//             address: "Junagarh Fort Road, Bikaner",
//             city: "Bikaner",
//             pincode: "334001",
//             latitude: 28.0230,
//             longitude: 73.3211,
//             googleMapUrl: "https://maps.google.com/?q=28.0230,73.3211",
//             nearestAirport: "Jodhpur Airport (251 km)",
//             nearestRailway: "Bikaner Junction (1 km)",
//             distanceFromCity: "In the heart of Bikaner city",
//         },
//         bestTimeToVisit: {
//             months: "November - February",
//             season: "Winter",
//             weather: "Cool, 5°C - 22°C",
//             tip: "Visit in the morning for fewer crowds. The fort looks beautiful in golden evening light.",
//         },
//         visitDuration: {
//             minimum: "1.5 Hours",
//             recommended: "2-3 Hours",
//             extended: "3-4 Hours (with museum and all palaces)",
//         },
//         highlights: [
//             "Anup Mahal (Gold Leaf Paintings)",
//             "Phool Mahal (Flower Palace)",
//             "Chandra Mahal (Moon Palace)",
//             "Karan Mahal",
//             "Never-Conquered Ground Fort",
//             "Royal Museum Collection",
//             "37 Palaces Inside",
//             "Prachina Museum",
//         ],
//         tags: ["Fort", "Museum", "Architecture", "Heritage", "History", "Desert City"],
//         facilities: [
//             "Parking",
//             "Restrooms",
//             "Audio Guide",
//             "Museum",
//             "Gift Shop",
//             "Guide Available",
//         ],
//         nearbyPlaces: [
//             "Lalgarh Palace (2 km)",
//             "Karni Mata Temple (33 km)",
//             "Camel Breeding Farm (8 km)",
//             "Rampuria Havelis (1 km)",
//         ],
//         dos: [
//             "Take the audio guide",
//             "Visit the Anup Mahal for stunning gold work",
//             "Explore the museum collections",
//             "Try Bikaneri bhujia and sweets nearby",
//         ],
//         donts: [
//             "Don't rush through - there's a lot to see",
//             "Don't touch the wall paintings",
//             "Don't miss the old city walk nearby",
//         ],
//         isOpen: true,
//         isFeatured: false,
//         isPopular: true,
//         isUNESCO: false,
//         yearBuilt: "1593 AD",
//         builtBy: "Raja Rai Singh",
//         architecture: "Rajput-Mughal (Sandstone & Marble)",
//         significance: "Only undefeated ground-level fort in Rajasthan",
//     },
// ];


export const DESTINATIONSOLD = [
    {
        id: 1,
        name: "Jaipur",
        slug: "jaipur",
        nickname: "The Pink City",
        description:
            "The capital of Rajasthan, known for its stunning pink-colored architecture, magnificent forts, and vibrant bazaars.",
        longDescription:
            "Jaipur, the Pink City, is a mesmerizing blend of history, culture, and modernity. Founded in 1727 by Maharaja Sawai Jai Singh II, it was the first planned city of India.",
        image: "https://images.unsplash.com/photo-1477584308802-e9c378852d9a?auto=format&fit=crop&w=1200&q=80",
        coverImage: "https://images.unsplash.com/photo-1524413840003-0587428385ad?auto=format&fit=crop&w=1200&q=80",
        gallery: [
            "https://images.unsplash.com/photo-1477584308802-e9c378852d9a?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1524413840003-0587428385ad?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1603262110263-fb0112e7cc33?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80"
        ],
        rating: 4.8,
        reviews: 12450,
        bestTime: "October - March",
        temperature: "12°C - 35°C",
        category: "Heritage City",
        attractions: ["Amber Fort", "Hawa Mahal", "City Palace", "Jantar Mantar"],
        highlights: ["Royal Architecture", "Shopping", "Cuisine", "Festivals"],
        distance: "268 km from Delhi",
        duration: "3-4 Days",
        price: 15000,
        tags: ["Heritage", "Culture", "Shopping", "Food"],
        isFeatured: true,
        isPopular: true,
        coordinates: { lat: 26.9124, lng: 75.7873 },
    },
    {
        id: 2,
        name: "Udaipur",
        slug: "udaipur",
        nickname: "The City of Lakes",
        description:
            "Romantic city of lakes and palaces, often called the Venice of the East. Home to the magnificent Lake Palace.",
        longDescription:
            "Udaipur, the City of Lakes, is one of the most romantic destinations in India. Founded by Maharana Udai Singh II in 1559.",
        image: "https://images.unsplash.com/photo-1586183189334-f83f4929f5c7?auto=format&fit=crop&w=1200&q=80",
        coverImage: "https://images.unsplash.com/photo-1615552980649-db3722e0325d?auto=format&fit=crop&w=1200&q=80",
        gallery: [
            "https://images.unsplash.com/photo-1586183189334-f83f4929f5c7?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1615552980649-db3722e0325d?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1590001155093-a3c66ab0c3ff?auto=format&fit=crop&w=1200&q=80"
        ],
        rating: 4.9,
        reviews: 15230,
        bestTime: "September - March",
        temperature: "10°C - 38°C",
        category: "Lake City",
        attractions: [
            "Lake Pichola",
            "City Palace",
            "Sajjangarh Palace",
            "Jag Mandir",
        ],
        highlights: ["Lakes", "Palaces", "Boat Rides", "Sunsets"],
        distance: "663 km from Delhi",
        duration: "3-5 Days",
        price: 18000,
        tags: ["Romantic", "Lakes", "Palaces", "Heritage"],
        isFeatured: true,
        isPopular: true,
        coordinates: { lat: 24.5854, lng: 73.7125 },
    },
    {
        id: 3,
        name: "Jodhpur",
        slug: "jodhpur",
        nickname: "The Blue City",
        description:
            "Dominated by the majestic Mehrangarh Fort, Jodhpur's blue-painted old city creates a stunning visual spectacle.",
        longDescription:
            "Jodhpur, known as the Blue City and Sun City, is the second-largest city in Rajasthan.",
        image: "https://images.unsplash.com/photo-1562141989-c5c79ac8f576?auto=format&fit=crop&w=1200&q=80",
        coverImage: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=1200&q=80",
        gallery: [
            "https://images.unsplash.com/photo-1562141989-c5c79ac8f576?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=1200&q=80"
        ],
        rating: 4.7,
        reviews: 9870,
        bestTime: "October - March",
        temperature: "8°C - 40°C",
        category: "Desert City",
        attractions: [
            "Mehrangarh Fort",
            "Umaid Bhawan Palace",
            "Jaswant Thada",
            "Clock Tower",
        ],
        highlights: ["Blue Houses", "Desert Views", "Royal Cuisine", "Handicrafts"],
        distance: "343 km from Jaipur",
        duration: "2-3 Days",
        price: 12000,
        tags: ["Heritage", "Desert", "Architecture", "Culture"],
        isFeatured: true,
        isPopular: true,
        coordinates: { lat: 26.2389, lng: 73.0243 },
    },
    {
        id: 4,
        name: "Jaisalmer",
        slug: "jaisalmer",
        nickname: "The Golden City",
        description:
            "Rising from the heart of the Thar Desert, the Golden City is home to a magnificent living fort and camel safaris.",
        longDescription:
            "Jaisalmer, the Golden City, is one of the most exotic destinations in India.",
        image: "https://images.unsplash.com/photo-1542401886-65d6c61db217?auto=format&fit=crop&w=1200&q=80",
        coverImage: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=1200&q=80",
        gallery: [
            "https://images.unsplash.com/photo-1542401886-65d6c61db217?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=1200&q=80"
        ],
        rating: 4.8,
        reviews: 11200,
        bestTime: "November - February",
        temperature: "5°C - 42°C",
        category: "Desert City",
        attractions: [
            "Jaisalmer Fort",
            "Sam Sand Dunes",
            "Patwon Ki Haveli",
            "Gadisar Lake",
        ],
        highlights: ["Camel Safari", "Sand Dunes", "Desert Camping", "Golden Fort"],
        distance: "575 km from Jaipur",
        duration: "3-4 Days",
        price: 14000,
        tags: ["Desert", "Adventure", "Heritage", "Camping"],
        isFeatured: true,
        isPopular: true,
        coordinates: { lat: 26.9157, lng: 70.9083 },
    },
    {
        id: 5,
        name: "Pushkar",
        slug: "pushkar",
        nickname: "The Sacred City",
        description:
            "One of the world's oldest cities, famous for its holy lake, Brahma Temple, and the legendary Pushkar Camel Fair.",
        longDescription:
            "Pushkar is one of the five sacred dhams for Hindus and is built around Pushkar Lake.",
        image: "https://images.unsplash.com/photo-1590001155093-a3c66ab0c3ff?auto=format&fit=crop&w=1200&q=80",
        coverImage: "https://images.unsplash.com/photo-1575377427642-087cf684ad0c?auto=format&fit=crop&w=1200&q=80",
        gallery: [
            "https://images.unsplash.com/photo-1590001155093-a3c66ab0c3ff?auto=format&fit=crop&w=1200&q=80",
            "https://images.unsplash.com/photo-1575377427642-087cf684ad0c?auto=format&fit=crop&w=1200&q=80"
        ],
        rating: 4.6,
        reviews: 7650,
        bestTime: "October - March",
        temperature: "8°C - 38°C",
        category: "Spiritual City",
        attractions: [
            "Pushkar Lake",
            "Brahma Temple",
            "Savitri Temple",
            "Camel Fair Ground",
        ],
        highlights: ["Holy Dip", "Camel Fair", "Spiritual Experience", "Markets"],
        distance: "145 km from Jaipur",
        duration: "2-3 Days",
        price: 8000,
        tags: ["Spiritual", "Culture", "Festival", "Heritage"],
        isFeatured: false,
        isPopular: true,
        coordinates: { lat: 26.4899, lng: 74.5511 },
    },
    {
        id: 6,
        name: "Mount Abu",
        slug: "mount-abu",
        nickname: "The Queen of Hills",
        description:
            "Rajasthan's only hill station offering a cool escape with the stunning Dilwara Temples and Nakki Lake.",
        longDescription:
            "Mount Abu is the only hill station in Rajasthan situated at 1,220 meters in the Aravalli Range.",
        image: "https://images.unsplash.com/photo-1477584308802-e9c378852d9a?auto=format&fit=crop&w=1200&q=80",
        coverImage: "https://images.unsplash.com/photo-1524413840003-0587428385ad?auto=format&fit=crop&w=1200&q=80",
        gallery: [
            "https://images.unsplash.com/photo-1477584308802-e9c378852d9a?auto=format&fit=crop&w=1200&q=80"
        ],
        rating: 4.5,
        reviews: 6540,
        bestTime: "November - February",
        temperature: "5°C - 33°C",
        category: "Hill Station",
        attractions: [
            "Dilwara Temples",
            "Nakki Lake",
            "Guru Shikhar",
            "Achalgarh Fort",
        ],
        highlights: ["Cool Climate", "Temples", "Lake Views", "Trekking"],
        distance: "490 km from Jaipur",
        duration: "2-3 Days",
        price: 10000,
        tags: ["Hill Station", "Spiritual", "Nature", "Trekking"],
        isFeatured: false,
        isPopular: true,
        coordinates: { lat: 24.5926, lng: 72.7156 },
    },
    {
        id: 7,
        name: "Bikaner",
        slug: "bikaner",
        nickname: "The Camel City",
        description:
            "A city of forts, temples, and havelis in the heart of the Thar Desert. Famous for Junagarh Fort and Bikaneri sweets.",
        longDescription:
            "Bikaner is a city in the northern part of the Thar Desert in Rajasthan, founded in 1488.",
        image: "https://images.unsplash.com/photo-1597075687490-8f673c6c17f6?auto=format&fit=crop&w=1200&q=80",
        coverImage: "https://images.unsplash.com/photo-1562141989-c5c79ac8f576?auto=format&fit=crop&w=1200&q=80",
        gallery: [
            "https://images.unsplash.com/photo-1597075687490-8f673c6c17f6?auto=format&fit=crop&w=1200&q=80"
        ],
        rating: 4.4,
        reviews: 5430,
        bestTime: "November - February",
        temperature: "5°C - 42°C",
        category: "Desert City",
        attractions: [
            "Junagarh Fort",
            "Camel Breeding Farm",
            "Karni Mata Temple",
            "Laxmi Niwas Palace",
        ],
        highlights: [
            "Camel Safari",
            "Fort Architecture",
            "Bikaneri Sweets",
            "Art",
        ],
        distance: "330 km from Jaipur",
        duration: "2-3 Days",
        price: 9000,
        tags: ["Desert", "Heritage", "Culture", "Food"],
        isFeatured: false,
        isPopular: false,
        coordinates: { lat: 28.0229, lng: 73.3119 },
    },
    {
        id: 8,
        name: "Ranthambore",
        slug: "ranthambore",
        nickname: "The Tiger Land",
        description:
            "One of India's premier wildlife destinations, famous for its tiger population and the 10th-century Ranthambore Fort.",
        longDescription:
            "Ranthambore National Park is one of the largest national parks in northern India.",
        image: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1200&q=80",
        coverImage: "https://images.unsplash.com/photo-1500627869374-13ad991b1116?auto=format&fit=crop&w=1200&q=80",
        gallery: [
            "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1200&q=80"
        ],
        rating: 4.7,
        reviews: 8970,
        bestTime: "October - June",
        temperature: "8°C - 45°C",
        category: "Wildlife",
        attractions: [
            "Tiger Safari",
            "Ranthambore Fort",
            "Padam Lake",
            "Jogi Mahal",
        ],
        highlights: [
            "Tiger Sightings",
            "Jeep Safari",
            "Bird Watching",
            "Fort",
        ],
        distance: "180 km from Jaipur",
        duration: "2-3 Days",
        price: 16000,
        tags: ["Wildlife", "Safari", "Nature", "Adventure"],
        isFeatured: true,
        isPopular: true,
        coordinates: { lat: 26.0173, lng: 76.5026 },
    },
];